### ISSUE TITLE
Add PostgreSQL Examples with Flex Shapes

### ISSUE THREAD

**Issue by dralquinta** [oracle-devrel/terraform-oci-cloudbricks-examples#19]
Please work in adding examples using Flex Shapes with different combinations such as single master, 1 standby and 2 standby options.

**Comment by dralquinta** [comment]
@Matt-Mcl can you work on this example pls?

**Comment by Matt-Mcl** [comment]
This should all already be possible @dralquinta by modifying values of variables. I'll test this now however.

**Comment by Matt-Mcl** [comment]
Ah - there is a problem. Working on this now.
